#!/usr/bin/env python3
import collections
import functools
import html
import io
import keyword
import os
import re
import sys
import tokenize
import traceback

__all__ = [
    "template_traceback",
    "template_to_function",
]

COMMENT_MARKER = "#"
STATEMENT_MARKER = "%"
VERBATIM_OUTPUT_MARKER = "="
OUTPUT_MARKER = "{"

TAG_PATTERNS = [
    (r"(?:{{|\s*{{-) ", r" (?:}}|-}}\s*)"),  # Output block (escaped)
    (r"(?:{%|\s*{%-) ", r" (?:%}|-%}\s*)"),  # Statement block
    (r"(?:{=|\s*{=-) ", r" (?:=}|-=}\s*)"),  # Verbatim output block
    (r"(?:{#|\s*{#-) ", r" (?:#}|-#}\s*)"),  # Comment block
]

# These keywords mark the start of a new indented block.
BLOCK_KEYWORDS = (
    "case",
    "elif",
    "else",
    "except",
    "finally",
    "for",
    "if",
    "match",
    "try",
    "while",
    "with",
)
# These are template-specific keywords that mark the end of an indented block.
END_BLOCK_KEYWORDS = (
    "endcase",
    "endfor",
    "endif",
    "endmatch",
    "endtry",
    "endwhile",
    "endwith",
)
# Sibling block keywords that are keywords that must appear after another,
# related block keyword at the same level of indentation.
SIBLING_BLOCK_KEYWORDS = (
    "elif",
    "else",
    "except",
    "finally",
)

CAPTURE_BLOCKS = (f"{opn}.*?{cls}" for opn, cls in TAG_PATTERNS)
CAPTURE_REGEX = re.compile(
    rf"(.*?)({'|'.join(CAPTURE_BLOCKS)})(.*?)|(.+?)\Z",
    re.MULTILINE | re.DOTALL,
)

TEMPLATE_PATH_PREFIX = "/._/python-templates/"

SCRIPT_PATH = os.path.abspath(__file__)


def soft_kw_as_var(tokens):
    """
    Given a list of tokens as generated by the "tokenize" module, determine
    whether a soft keyword is being used as as variable. This is only intended
    to be used inside of "{% ... %}" statement blocks, so it does not catch
    every valid construct.

    Arguments:
    - tokens

    Return: True if a soft keyword is used as a variable (e.g. `match =
    re.match(...)` or `case = Table.CaseName`) or False otherwise.
    """
    if len(tokens) == 1:
        return keyword.issoftkeyword(tokens[0].string)

    if len(tokens) < 3 or not keyword.issoftkeyword(tokens[0].string):
        return False

    return tokens[1].string.endswith("=") or tokens[1].string.startswith("(")


@functools.lru_cache()
def compile_template(path):
    """
    Convert template located at `path` to Python code object.
    """
    with open(path) as iostream:
        template_source = iostream.read()

    block_counts = collections.defaultdict(int)
    depth = 0
    line_count = 0
    count_cursor = 0
    span_map = dict()
    python_source = [
        # As the template is parsed, a dictionary is generated and placed here,
        # at the beginning of transpiled script, that maps lines of the
        # transpiled source to lines of the template and byte offsets where
        # interpolated tags start.
        "<Reserved for template offset table.>",
    ]

    def add_line(text):
        """
        Helper function for adding lines to generated Python script.
        """
        python_source.append(" " * depth + text)

    def add_raw_text(text):
        """
        Helper function for inserting raw text into the generated script.
        """
        if not text:
            return

        if block_counts["match"] <= block_counts["case"]:
            add_line("_template_output.append(" + repr(text) + ")")
        elif not text.isspace():
            raise SyntaxError(
                'Text cannot appear inside of a "match" block unless it is'
                ' also inside a "case" block'
            )

    # This could be made more efficient by complicating the regular expressions
    # and using named capture groups to avoid needlessly modifying strings and
    # checking characters, but I don't think the additional complexity is worth
    # it right now.
    for match in CAPTURE_REGEX.finditer(template_source):
        before, tag, after, tail = match.groups()

        if tag:
            add_raw_text(before)

            # These values are used to update the span map with the information
            # needed to map transpiled lines to their location inside the
            # template.
            tag_start, tag_end = match.span(2)
            tag_start += tag.index("{")
            lineno = template_source.count("\n", None, tag_start) + 1
            width = tag_end - tag_start
            tag_start_line = len(python_source)

            tag = tag.strip()
            contents = tag[3:-3].strip()
            marker = tag[1]

            if marker == COMMENT_MARKER:
                pass

            elif marker == STATEMENT_MARKER:
                string_fd = io.StringIO(contents)
                tokens = list(tokenize.generate_tokens(string_fd.readline))
                first = tokens[0].string

                if any(map(lambda x: x.string == ";", tokens)):
                    raise SyntaxError(
                        "Semicolons as line endings are not supported in tags",
                        (path, lineno, None, None)
                    )

                # Strip out newline tokens. This makes it possible for template
                # statements and expressions to span multiple lines without the
                # user having to use parentheses or "\" at the end of a line.
                contents = tokenize.untokenize(
                    t for t in tokens if t.string != "\n"
                )

                if first in BLOCK_KEYWORDS and not soft_kw_as_var(tokens):
                    if not contents.endswith(":"):
                        contents += ":"

                    if first in SIBLING_BLOCK_KEYWORDS:
                        depth -= 1
                    else:
                        block_counts[first] += 1

                    add_line(contents)

                    depth += 1
                elif first in END_BLOCK_KEYWORDS:
                    if contents != first:
                        raise SyntaxError(
                            "Block end tags cannot contain other text",
                            (path, lineno, None, None)
                        )

                    block_counts[first[3:]] -= 1
                    depth -= 1
                else:
                    add_line(contents)

            elif marker in (OUTPUT_MARKER, VERBATIM_OUTPUT_MARKER):
                # Double parentheses ensures that something like "{{ x = 1 }}"
                # produces a less confusing error:
                #
                #     >>> str((x = 1))
                #       File "<stdin>", line 1
                #         str((x=1))
                #               ^
                #     SyntaxError: invalid syntax
                #     >>> str(x=1)
                #     Traceback (most recent call last):
                #       File "<stdin>", line 1, in <module>
                #     TypeError: 'x' is an invalid keyword argument for ...
                #
                contents = f"str(({contents}))"

                if tag[1] == OUTPUT_MARKER:
                    contents = f"_template_escaper({contents})"

                add_line(f"_template_output.append({contents})")

            else:
                # This should be unreachable.
                raise RuntimeError(f"Unrecognized tag marker {marker!r}")

            for entry in python_source[count_cursor:tag_start_line]:
                line_count += 1 + entry.count("\n")

            count_cursor = tag_start_line
            span_map[line_count + 1] = (lineno, tag_start, width)

        add_raw_text(after or tail)

    if depth:
        messages = list()
        text = "the number of %ss is %s than the number of %ss by %d"

        for block, count in block_counts.items():
            if not count:
                continue

            difference = "less" if count < 0 else "greater"
            message = text % (block, difference, "end" + block, abs(count))
            messages.append(message)

        all_messages = ", and ".join(messages).replace("t", "T", 1) + "."
        raise SyntaxError(all_messages)

    python_source[0] = f"_template_span_map[{path!r}] = {span_map!r}"
    script = "\n".join(python_source)

    try:
        return compile(script, TEMPLATE_PATH_PREFIX + path, "exec")
    except SyntaxError as error:
        error.filename = path
        error.offset = -1

        while error.lineno > 0:
            # It's possible that a given line number isn't in the span map, so
            # the line number in the exception is decremented until a line
            # that's actually in the map is found.
            if error.lineno in span_map:
                error.lineno, true_offset, _ = span_map[error.lineno]
                nl = template_source.find("\n", true_offset)
                nl = None if nl < 0 else nl
                error.text = template_source[true_offset:nl]
                break
            else:
                error.lineno -= 1
        else:
            error.lineno = -1

        raise


def template_to_function(path, escaper=html.escape):
    """
    Convert template into a callable function. By default, the template output
    will be made HTML-safe, but the content escape method can be changed by
    setting the `escaper` argument.

    The resulting function action can be called using two different conventions
    to pass state into the template. One way to pass state into the function is
    to provide variable names and values as keyword arguments to the function:

    >>> render_inbox = template_to_function("inbox.html")
    >>> html = render_inbox(title="Inbox", email="j.doe@example.com")

    Once execution is finished, any state defined only within the template is
    lost. Alternatively, the template function can be called with a dictionary
    as an argument:

    >>> render_inbox = template_to_function("inbox.html")
    >>> variables = {
    ...     "title": "Inbox",
    ...     "email": "j.doe@example.com",
    ... }
    >>> html = render_inbox(variables)

    Within the template, all members of the dictionary will be accessible as
    variables. When template execution is finished, all of the template's state
    will be preserved in the dictionary; any modified or newly defined
    variables will be reflected in dictionary. Continuing from the example
    above, if the template contained a statement like "{% name = ... %}", the
    dictionary would contain a new key after the template was rendered:

    >>> variables
    {'name': 'Jess Doe', 'email': 'j.doe@example.com', 'title': 'Home Page'}

    To avoid conflicting with definitions used internally by the template
    system, no user-defined variable names may start with "_template_". If an
    error is raised during template execution, the dictionary may contain
    internal variables starting with this prefix.
    """
    abspath = os.path.abspath(path)
    compiled_template = compile_template(abspath)
    template_directory = os.path.dirname(abspath)

    def function(_template_symbol_dictionary=None, **symbols):
        if _template_symbol_dictionary is not None and symbols:
            raise ValueError(
                "Cannot specify _template_symbol_dictionary when using "
                "keyword arguments as template variables."
            )
        elif _template_symbol_dictionary:
            symbols = _template_symbol_dictionary

        symbols["_template_escaper"] = escaper

        if "_template_output" in symbols:
            is_include_call = True

        else:
            def include(path, raw=False, escaper=None):
                """
                Incorporate `path` into template output. If `raw` is `False`,
                the file will be parsed as a template and executed, but if
                `raw` is `True`, the contents of the file will be incorporated
                into the output verbatim. Normally, the escape function of the
                calling template will be used to escape the included template,
                but this can be overridden by setting `escaper`. If `path` is a
                relative path, it will be interpreted as being relative to the
                directory of the calling template. Note that this function does
                not return the included data.
                """
                path = os.path.join(template_directory, path)
                if raw:
                    if escaper:
                        raise ValueError("Cannot set escaper when raw=True.")
                    with open(path) as iostream:
                        contents = iostream.read()
                    symbols["_template_output"].append(contents)
                else:
                    my_escaper = symbols["_template_escaper"]
                    if escaper is None:
                        escaper = my_escaper
                    try:
                        template_to_function(path, escaper=escaper)(symbols)
                    finally:
                        symbols["_template_escaper"] = my_escaper

            def raw_include(path):
                """
                Helper function to call `include` with `raw=True`; the
                following two expressions are equivalent:

                >>> raw_include("file.txt")
                >>> include("file.txt", raw=True)
                """
                include(path, raw=True)

            def defined(name):
                """
                Return boolean value indicating whether or not a variable is
                defined. The `name` is given as a string.
                """
                return name in symbols

            is_include_call = False
            symbols.update({
                "_template_output": list(),
                "_template_span_map": dict(),
                "defined": defined,
                "include": include,
                "raw_include": raw_include,
            })

        try:
            exec(compiled_template, symbols)
            output = "".join(symbols["_template_output"])
            if not is_include_call:
                del symbols["_template_span_map"]
            return output
        finally:
            if not is_include_call:
                del symbols["_template_output"]
                del symbols["defined"]
                del symbols["include"]
                del symbols["raw_include"]

    return function


def template_traceback(templates_only=False):
    """
    An exception raised inside of a template will produce a traceback that can
    be hard to follow. When this function is called within an
    exception-handling block, it returns a sanitized traceback in the form of a
    string that correctly maps locations in the stack to the corresponding
    locations in the templates.

    This is what a standard stack trace looks like when an exception is raised
    within a template:

        Traceback (most recent call last):
          File "app.py", line 412, in <module>
            main()
          File "app.py", line 253, in main
            print(admin_page())
          File ".../tipyte:.py", line 376, in function
            exec(compiled_template, dict(), symbols)
          File "/._/python-templates/.../admin.html", line 3, in <module>
            <div class="container-fluid">
          File ".../tipyte.py", line 345, in include
            template_to_function(path, escaper=escaper)(symbols)
          File ".../tipyte.py", line 376, in function
            exec(compiled_template, dict(), symbols)
          File "/._/python-templates/.../user-list.html", line 3, in <module>
            <ul>
        NameError: name 'query' is not defined

    This is what the sanitized stack trace returned by this function looks
    like:

        Traceback (most recent call last):
          File "app.py", line 412, in <module>
            main()
          File "app.py", line 253, in main
            print(admin_page())
          File ".../admin.html", line 5, in <module>
            {% include("user-list.html") %}
          File ".../user-list.html", line 4, in <module>
            {% for username, country, status in query("SELECT * FROM Users") %}
        NameError: name 'query' is not defined

    Do not use this function when handling a `SyntaxError`. Any syntax errors
    generated from within a template will already have been modified to include
    all the information needed to easily determine where the syntax error is.
    When the `templates_only` option is set, the only files that will be shown
    in the traceback are templates; lines from pure-Python files will be
    elided. If `templates_only` were set, the following traceback would be
    returned lieu of the one above:

        Traceback (most recent call last):
          File ".../admin.html", line 5, in <module>
            {% include("user-list.html") %}
          File ".../user-list.html", line 4, in <module>
            {% for username, country, status in query("SELECT * FROM Users") %}
        NameError: name 'query' is not defined

    Example usage:

    >>> render_home_page = template_to_function("home.html")
    ... try:
    ...     render_home_page(date="January 10th, 2016")
    ... except Exception as error:
    ...     if not isinstance(error, SyntaxError):
    ...         error.template_traceback = template_traceback()
    ...     raise
    """
    _, error, trace = sys.exc_info()

    frames = list()

    for frame in traceback.extract_tb(trace):
        path, lineno, call, text = frame

        if path.startswith(TEMPLATE_PATH_PREFIX):
            path = path[len(TEMPLATE_PATH_PREFIX):]
            span_map = trace.tb_frame.f_locals["_template_span_map"][path]
            text = None

            try:
                # Search backward in the span map until we find a line that
                # exists since we don't have entries for every line.
                while lineno and lineno not in span_map:
                    lineno -= 1

                lineno, start, width = span_map[lineno]

                with open(path) as iostream:
                    iostream.read(start)  # Because "seek" is based on bytes.
                    text = iostream.read(width).replace("\n", " ").strip()
            except Exception:
                pass

            frames.append((path, lineno, call, text))

        elif not templates_only and not os.path.samefile(path, SCRIPT_PATH):
            frames.append(frame)

        trace = trace.tb_next

    if frames:
        prefix = "Traceback (most recent call last):\n"
        middle = "".join(traceback.format_list(frames))
        suffix = error.__class__.__name__ + ": " + str(error)
        return prefix + middle + suffix
